version: '2'
services:
  jenkins:
    image: 'local-jenkins:latest'
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - 'jenkins_data:/bitnami'
volumes:
  jenkins_data:
    driver: local
##user: user, password: bitnami



